import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  grammarSidebar: [{type: 'autogenerated', dirName: 'grammar'}],
  vocabularySidebar: [{type: 'autogenerated', dirName: 'vocabulary'}],
  pronunciationSidebar: [{type: 'autogenerated', dirName: 'pronunciation'}],
  readingSidebar: [{type: 'autogenerated', dirName: 'reading'}],
  writingSidebar: [{type: 'autogenerated', dirName: 'writing'}],
  listeningSidebar: [{type: 'autogenerated', dirName: 'listening'}],
};

export default sidebars;
